### ISSUE TITLE
Consider accessibility implications of only displaying consultant names on hover

### ISSUE THREAD

**Issue by pnodseth** [Kodeworks/kodeworks.no#13]
People not using a mouse will not be able to see names.
Also, seems like names appear on smaller devices like phones, but not on medium devices like iPads.

**Comment by tmn** [comment]
@pnodseth could something like this work? Always showing text + make the backdrop a bit darker. 

<img width="1141" alt="Screenshot 2022-05-13 at 08 35 50" src="https://user-images.githubusercontent.com/193333/168225326-e998ad0b-6c34-4911-b5d8-319705a418fc.png">

**Comment by pnodseth** [comment]
I think that looks really good 👍 
Small suggestion/not important: Project tags stand out quite heavily now with the solid black backgorund and green underline. How about making them a bit more subtle, maybe no/lighter background color?

**Comment by tmn** [comment]
Will be testing out alternatives on the links. Great feedback. Thanks!
